apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: sompornic/my-app:v1.x.x
    argocd-image-updater.argoproj.io/myapp.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
spec:
  project: default
  source:
    repoURL: 'https://github.com/sompornic/node-be.git'
    targetRevision: develop
    path: dev # ใส่ path ที่มี deployment.yaml
  destination:
    server: 'https://kubernetes.default.svc' # ใช้ค่า default สำหรับ cluster ปัจจุบัน
    namespace: my-app # Namespace ที่ต้องการ deploy
  syncPolicy:
    automated: 
      prune: true # ลบ resource ที่ไม่จำเป็น  
      selfHeal: true # Sync ใหม่เมื่อพบความคลาดเคลื่อน