apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc' # ใช้ค่า default สำหรับ cluster ปัจจุบัน
    namespace: kustomize-app # Namespace ที่ต้องการ deploy
  project: default
  source:
    repoURL: 'https://github.com/sompornic/argocd-example-apps.git'
    targetRevision: master
    path: kustomize-app
    kustomize:
      namePrefix: test-
      commonLabels:
        app: demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true