apiVersion: v1
kind: Service
metadata:
  name: kustomize-app-service
spec:
  selector:
    app: kustomize-app-service
  ports:
    - protocol: TCP
      port: 3000            # พอร์ตที่ Service จะเปิดใน Cluster
      targetPort: 80      # พอร์ตที่ Pod ใช้ (ต้องตรงกับ containerPort ใน Deployment)
      # nodePort: 30000     # พอร์ตที่จะ expose บน Node (สามารถกำหนดเองได้ในช่วง 30000-32767)
  type: NodePort         # ประเภท Service เป็น NodePort