name: Update Kustomize Image Tag

on:
  push:
    branches:
      - master  # ทำงานเมื่อมีการ Push ไปยัง branch main

jobs:
  update-kustomize:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user identity
        run: |
          git config --global user.name ${{ secrets.USER_NAME_GIT }}
          git config --global user.email ${{ secrets.EMAIL_GIT }}


      - name: Get Git Commit Hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update kustomization.yaml with new image tag
        run: |
          ls -l
          cd kustomize-app
          sed -i "s/newTag:.*/newTag: $COMMIT_HASH/" kustomization.yaml
          git add kustomization.yaml
          git commit -m "Update image tag to $COMMIT_HASH"
      - name: Push changes to repository
        run: |
          git push https://github-actions:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:master
